In [62]:
import pandas as pd
import numpy as np
from itertools import compress

In [126]:
def tsv_to_dataframe(file_tsv, structure = "normal"):
    '''
    this function transforms Eurostat tsv file in pandas dataframe
    file_tsv: file name. It's work with tsv and compressed file "tsv.gz"
    '''
    
    if structure == "inverse":
        print("use tsv_to_dataframe_long instead tsv_to_dataframe")
    
    def clean_cells(x):
        '''This function transforms Eurostat Missing Values ": " in numpy missing values.
        Then clean Eurostat annotation "b, u, .."'''
        try:
            return float(x)
        except:
            try:
                return float(x.split(" ")[0])
            except:
                return np.nan
    # open the Eurostat TSV file 

    data = pd.read_csv(file_tsv, sep="\t")
    # Create a dataframe for values data
    data_clean = data
    # Clean data values with clean_cells function
    data_clean = data_clean.applymap(lambda x: clean_cells(x))
    # Drop column with variable name like "age,isced11,unit,sex,geo\time". It is the first column. we have a 
    # dataframe with only data values 
    data_clean.drop(data_clean.columns[0], axis = 1, inplace = True)
    # transform column with variable in multiple-columns  
    variabili = data[data.columns[0]].apply(lambda x: pd.Series(x.split(",")))
    variabili.columns = data.columns[0].split(",")
    # return cleaned dataframe in pandas dataframe
    return pd.concat([variabili, data_clean], axis = 1)

In [127]:
def tsv_to_dataframe_long(file_tsv, structure = "normal"):
    '''
    this function transforms Eurostat tsv file in pandas dataframe
    file_tsv: file name. It's work with tsv and compressed file "tsv.gz"
    structure: "normal", columns indicates time
    structure: "inverse", columns indicates Nuts / geo
    
    '''
    
    def clean_cells(x):
        '''This function transforms Eurostat Missing Values ": " in numpy missing values.
        Then clean Eurostat annotation "b, u, .."'''
        try:
            return float(x)
        except:
            try:
                return float(x.split(" ")[0])
            except:
                return np.nan
            
    def annotation(x):
            '''This function extracts Eurostat annotation "b, u, .."'''
            try:
                return x.split(" ")[1]
            except:
                return np.nan

    def columns_type(x):
            try:
                return int(x.strip())
            except:
                if x == "geo\\time":
                    return "var_" + "geo"
                else:
                    return "var_" + x
                
    
    def columns_type_inverse(columns):
        new_columns =[]
        sep = columns.get_loc("time\\geo")
        new_columns.extend(list(columns[:sep].map(lambda x: "var_" + x)))
        new_columns.append("var_time")
        new_columns.extend(list(columns[sep + 1:]))
        return new_columns
    
    # open the Eurostat TSV file 

    data = pd.read_csv(file_tsv, sep="\t")
    # Create a dataframe for values data
    data_clean = data
    # Clean data values with clean_cells function
    data_clean = data_clean.applymap(lambda x: x)
    # Drop column with variable name like "age,isced11,unit,sex,geo\time". It is the first column. we have a 
    # dataframe with only data values 
    data_clean.drop(data_clean.columns[0], axis = 1, inplace = True)
    # transform column with variable in multiple-columns  
    variabili = data[data.columns[0]].apply(lambda x: pd.Series(x.split(",")))
    variabili.columns = data.columns[0].split(",")
    # return cleaned dataframe in pandas dataframe
    result = pd.concat([variabili, data_clean], axis = 1)
    
    if structure == "normal":
        colonne  = list(map(lambda x: columns_type(x), list(result.columns.values)))
        result.columns = colonne
        colonne_var = result.columns.map(lambda x: str(x)[0:3] == "var")
        index = list(compress(result.columns, colonne_var))
        result = result.melt(id_vars = index)
        result["value_raw"] = result["value"]
        result["eurostat_annotation"] = result["value_raw"].apply(lambda x: annotation(x))
        result["value"] = result["value"].apply(clean_cells) 
    elif structure == "inverse":
        result.columns = columns_type_inverse(result.columns)
        colonne_var = result.columns.map(lambda x: str(x)[0:3] == "var")
        index = list(compress(result.columns, colonne_var))
        result = result.melt(id_vars = index, var_name = "geo")
        result["value_raw"] = result["value"]
        result["eurostat_annotation"] = result["value_raw"].apply(lambda x: annotation(x))
        result["value"] = result["value"].apply(clean_cells) 
        
    
    return result

In [128]:
#example 
#if __name__ == "__main__":
import urllib.request
import gzip

eurostat_link = "http://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&file=data%2Fhlth_dlm030.tsv.gz"
urllib.request.urlretrieve(eurostat_link , "file.tsv.gz")

('file.tsv.gz', <http.client.HTTPMessage at 0x7f5cdc5ce6a0>)

In [129]:
result = tsv_to_dataframe_long("file.tsv.gz", structure = "inverse")

In [130]:
result

,var_unit,var_hlth_pb,var_age,var_sex,var_time,geo,value,value_raw,eurostat_annotation
0,PC,PB1040,TOTAL,F,2011,EU28,12.0,12,NaN
1,PC,PB1040,TOTAL,M,2011,EU28,12.2,12.2,NaN
2,PC,PB1040,TOTAL,T,2011,EU28,12.1,12.1,NaN
3,PC,PB1040,Y15-24,F,2011,EU28,21.9,21.9,NaN
4,PC,PB1040,Y15-24,M,2011,EU28,25.5,25.5,NaN
5,PC,PB1040,Y15-24,T,2011,EU28,23.7,23.7,NaN
6,PC,PB1040,Y25-34,F,2011,EU28,17.0,17,NaN
7,PC,PB1040,Y25-34,M,2011,EU28,13.9,13.9,NaN
8,PC,PB1040,Y25-34,T,2011,EU28,15.4,15.4,NaN
9,PC,PB1040,Y25-64,F,2011,EU28,11.5,11.5,NaN
10,PC,PB1040,Y25-64,M,2011,EU28,11.5,11.5,NaN
11,PC,PB1040,Y25-64,T,2011,EU28,11.5,11.5,NaN
12,PC,PB1040,Y35-44,F,2011,EU28,13.1,13.1,NaN
13,PC,PB1040,Y35-44,M,2011,EU28,12.3,12.3,NaN
14,PC,PB1040,Y35-44,T,2011,EU28,12.7,12.7,NaN
15,PC,PB1040,Y45-54,F,2011,EU28,10.5,10.5,NaN
16,PC,PB1040,Y45-54,M,2011,EU28,10.8,10.8,NaN
17,PC,PB1040,Y45-54,T,2011,EU28,10.6,10.6,NaN
18,PC,PB1040,Y55-64,F,2011,EU28,8.8,8.8,NaN
19,PC,PB1040,Y55-64,M,2011,EU28,10.8,10.8,NaN
20,PC,PB1040,Y55-64,T,2011,EU28,9.8,9.8,NaN
21,PC,PB1041,TOTAL,F,2011,EU28,9.8,9.8,NaN
22,PC,PB1041,TOTAL,M,2011,EU28,9.5,9.5,NaN
23,PC,PB1041,TOTAL,T,2011,EU28,9.6,9.6,NaN
24,PC,PB1041,Y15-24,F,2011,EU28,20.9,20.9,NaN
25,PC,PB1041,Y15-24,M,2011,EU28,21.9,21.9,NaN
26,PC,PB1041,Y15-24,T,2011,EU28,21.4,21.4,NaN
27,PC,PB1041,Y25-34,F,2011,EU28,11.3,11.3,NaN
28,PC,PB1041,Y25-34,M,2011,EU28,10.6,10.6,NaN
29,PC,PB1041,Y25-34,T,2011,EU28,10.9,10.9,NaN
...,...,...,...,...,...,...,...,...,...
2658,PC,PB1070,Y35-44,F,2011,TR,5.2,5.2,NaN
2659,PC,PB1070,Y35-44,M,2011,TR,9.4,9.4,NaN
2660,PC,PB1070,Y35-44,T,2011,TR,7.9,7.9,NaN
2661,PC,PB1070,Y45-54,F,2011,TR,2.7,2.7,NaN
2662,PC,PB1070,Y45-54,M,2011,TR,7.9,7.9,NaN
2663,PC,PB1070,Y45-54,T,2011,TR,5.8,5.8,NaN
2664,PC,PB1070,Y55-64,F,2011,TR,0.9,0.9,NaN
2665,PC,PB1070,Y55-64,M,2011,TR,5.7,5.7,NaN
2666,PC,PB1070,Y55-64,T,2011,TR,3.7,3.7,NaN
2667,PC,PB1071,TOTAL,F,2011,TR,10.9,10.9,NaN
2668,PC,PB1071,TOTAL,M,2011,TR,8.1,8.1,NaN
2669,PC,PB1071,TOTAL,T,2011,TR,8.9,8.9,NaN
2670,PC,PB1071,Y15-24,F,2011,TR,18.6,18.6,NaN
2671,PC,PB1071,Y15-24,M,2011,TR,14.9,14.9,NaN
2672,PC,PB1071,Y15-24,T,2011,TR,16.2,16.2,NaN
2673,PC,PB1071,Y25-34,F,2011,TR,12.0,12,NaN
2674,PC,PB1071,Y25-34,M,2011,TR,7.9,7.9,NaN
2675,PC,PB1071,Y25-34,T,2011,TR,9.1,9.1,NaN
2676,PC,PB1071,Y25-64,F,2011,TR,8.6,8.6,NaN
2677,PC,PB1071,Y25-64,M,2011,TR,6.8,6.8,NaN
2678,PC,PB1071,Y25-64,T,2011,TR,7.3,7.3,NaN
2679,PC,PB1071,Y35-44,F,2011,TR,6.6,6.6,NaN
2680,PC,PB1071,Y35-44,M,2011,TR,5.5,5.5,NaN
2681,PC,PB1071,Y35-44,T,2011,TR,5.8,5.8,NaN
2682,PC,PB1071,Y45-54,F,2011,TR,5.8,5.8,NaN
2683,PC,PB1071,Y45-54,M,2011,TR,6.5,6.5,NaN
2684,PC,PB1071,Y45-54,T,2011,TR,6.3,6.3,NaN
2685,PC,PB1071,Y55-64,F,2011,TR,2.3,2.3,NaN
2686,PC,PB1071,Y55-64,M,2011,TR,6.4,6.4,NaN
2687,PC,PB1071,Y55-64,T,2011,TR,5.5,5.5,NaN

In [97]:
columns_type_inverse(result.columns)

['var_unit',
 'var_hlth_pb',
 'var_age',
 'var_sex',
 'time',
 'geo_EU28 ',
 'geo_BE ',
 'geo_BG ',
 'geo_CZ ',
 'geo_DK ',
 'geo_DE ',
 'geo_EE ',
 'geo_IE ',
 'geo_EL ',
 'geo_ES ',
 'geo_FR ',
 'geo_HR ',
 'geo_IT ',
 'geo_CY ',
 'geo_LV ',
 'geo_LT ',
 'geo_LU ',
 'geo_HU ',
 'geo_MT ',
 'geo_NL ',
 'geo_AT ',
 'geo_PL ',
 'geo_PT ',
 'geo_RO ',
 'geo_SI ',
 'geo_SK ',
 'geo_FI ',
 'geo_SE ',
 'geo_UK ',
 'geo_IS ',
 'geo_CH ',
 'geo_TR ']

In [72]:
        
            try:
                return int(x.strip())
            except:
                if x == "time\\geo":
                    return "var_" + "geo"
                else:
                    return "var_" + x

Empty DataFrame
Columns: [var_unit, var_hlth_pb, var_age, var_sex, var_time\geo, var_EU28 , var_BE , var_BG , var_CZ , var_DK , var_DE , var_EE , var_IE , var_EL , var_ES , var_FR , var_HR , var_IT , var_CY , var_LV , var_LT , var_LU , var_HU , var_MT , var_NL , var_AT , var_PL , var_PT , var_RO , var_SI , var_SK , var_FI , var_SE , var_UK , var_IS , var_CH , var_TR , variable, value, value_raw, eurostat_annotation]
Index: []

[0 rows x 41 columns]

In [51]:
result = tsv_to_dataframe_long("file.tsv.gz")
result

,var_itm_newa,var_indic_ag,var_unit,var_geo,variable,value,value_raw,eurostat_annotation
0,01000,PROD_BP,MIO_EUR,AT,2017,857.51,857.51 e,e
1,01000,PROD_BP,MIO_EUR,BE,2017,393.61,393.61 e,e
2,01000,PROD_BP,MIO_EUR,BG,2017,1136.57,1136.57 e,e
3,01000,PROD_BP,MIO_EUR,CH,2017,290.24,290.24 e,e
4,01000,PROD_BP,MIO_EUR,CY,2017,11.99,11.99 e,e
5,01000,PROD_BP,MIO_EUR,CZ,2017,1062.51,1062.51 e,e
6,01000,PROD_BP,MIO_EUR,DE,2017,4530.67,4530.67 e,e
7,01000,PROD_BP,MIO_EUR,DK,2017,1761.17,1761.17 e,e
8,01000,PROD_BP,MIO_EUR,EA11,2017,26275.97,26275.97 e,e
9,01000,PROD_BP,MIO_EUR,EA12,2017,27068.94,27068.94 e,e
10,01000,PROD_BP,MIO_EUR,EA16,2017,27687.53,27687.53 e,e
11,01000,PROD_BP,MIO_EUR,EA19,2017,29190.75,29190.75 e,e
12,01000,PROD_BP,MIO_EUR,EE,2017,215.69,215.69 e,e
13,01000,PROD_BP,MIO_EUR,EL,2017,792.97,792.97 e,e
14,01000,PROD_BP,MIO_EUR,ES,2017,3293.19,3293.19 e,e
15,01000,PROD_BP,MIO_EUR,EU15,2017,32865.12,32865.12 e,e
16,01000,PROD_BP,MIO_EUR,EU25,2017,41732.66,41732.66 e,e
17,01000,PROD_BP,MIO_EUR,EU27,2017,47182.21,47182.21 e,e
18,01000,PROD_BP,MIO_EUR,EU28,2017,47749.82,47749.82 e,e
19,01000,PROD_BP,MIO_EUR,FI,2017,419.28,419.28 e,e
20,01000,PROD_BP,MIO_EUR,FR,2017,12450.13,12450.13 e,e
21,01000,PROD_BP,MIO_EUR,HR,2017,567.60,567.60 e,e
22,01000,PROD_BP,MIO_EUR,HU,2017,1989.43,1989.43 e,e
23,01000,PROD_BP,MIO_EUR,IE,2017,337.49,337.49 e,e
24,01000,PROD_BP,MIO_EUR,IS,2017,NaN,:,
25,01000,PROD_BP,MIO_EUR,IT,2017,3344.59,3344.59 e,e
26,01000,PROD_BP,MIO_EUR,LT,2017,893.53,893.53 e,e
27,01000,PROD_BP,MIO_EUR,LU,2017,22.77,22.77 e,e
28,01000,PROD_BP,MIO_EUR,LV,2017,394.00,394.00 e,e
29,01000,PROD_BP,MIO_EUR,MK,2017,NaN,:,
...,...,...,...,...,...,...,...,...
2337855,35000,PROD_BP,MIO_PPS,EA16,1973,NaN,:,
2337856,35000,PROD_BP,MIO_PPS,EA19,1973,NaN,:,
2337857,35000,PROD_BP,MIO_PPS,EE,1973,NaN,:,
2337858,35000,PROD_BP,MIO_PPS,EL,1973,NaN,:,
2337859,35000,PROD_BP,MIO_PPS,ES,1973,NaN,:,
2337860,35000,PROD_BP,MIO_PPS,EU15,1973,NaN,:,
2337861,35000,PROD_BP,MIO_PPS,EU25,1973,NaN,:,
2337862,35000,PROD_BP,MIO_PPS,EU27,1973,NaN,:,
2337863,35000,PROD_BP,MIO_PPS,EU28,1973,NaN,:,
2337864,35000,PROD_BP,MIO_PPS,FI,1973,NaN,:,
2337865,35000,PROD_BP,MIO_PPS,FR,1973,NaN,:,
2337866,35000,PROD_BP,MIO_PPS,HR,1973,NaN,:,
2337867,35000,PROD_BP,MIO_PPS,HU,1973,NaN,:,
2337868,35000,PROD_BP,MIO_PPS,IE,1973,NaN,:,
2337869,35000,PROD_BP,MIO_PPS,IS,1973,NaN,:,
2337870,35000,PROD_BP,MIO_PPS,IT,1973,NaN,:,
2337871,35000,PROD_BP,MIO_PPS,LT,1973,NaN,:,
2337872,35000,PROD_BP,MIO_PPS,LU,1973,NaN,:,
2337873,35000,PROD_BP,MIO_PPS,LV,1973,NaN,:,
2337874,35000,PROD_BP,MIO_PPS,MK,1973,NaN,:,
2337875,35000,PROD_BP,MIO_PPS,MT,1973,NaN,:,
2337876,35000,PROD_BP,MIO_PPS,NL,1973,NaN,:,
2337877,35000,PROD_BP,MIO_PPS,NO,1973,NaN,:,
2337878,35000,PROD_BP,MIO_PPS,PL,1973,NaN,:,
2337879,35000,PROD_BP,MIO_PPS,PT,1973,NaN,:,
2337880,35000,PROD_BP,MIO_PPS,RO,1973,NaN,:,
2337881,35000,PROD_BP,MIO_PPS,SE,1973,NaN,:,
2337882,35000,PROD_BP,MIO_PPS,SI,1973,NaN,:,
2337883,35000,PROD_BP,MIO_PPS,SK,1973,NaN,:,
2337884,35000,PROD_BP,MIO_PPS,UK,1973,NaN,:,

In [53]:
#Python library

import tsv_to_pandas

In [56]:
eurostat_link = "http://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&file=data%2Fhlth_dlm030.tsv.gz"
urllib.request.urlretrieve(eurostat_link , "file.tsv.gz")

('file.tsv.gz', <http.client.HTTPMessage at 0x7f5ce9fef2b0>)

In [ ]:
result = tsv_to_pandas.tsv_to_dataframe("file.tsv.gz")

In [59]:
result.columns[4]

'time\\geo'

In [11]:
result = tsv_to_pandas.tsv_to_dataframe_long("file.tsv.gz")
result

,var_itm_newa,var_indic_ag,var_unit,var_geo,variable,value,value_raw,eurostat_annotation
0,01000,PROD_BP,MIO_EUR,AT,2017,857.51,857.51 e,e
1,01000,PROD_BP,MIO_EUR,BE,2017,393.61,393.61 e,e
2,01000,PROD_BP,MIO_EUR,BG,2017,1136.57,1136.57 e,e
3,01000,PROD_BP,MIO_EUR,CH,2017,290.24,290.24 e,e
4,01000,PROD_BP,MIO_EUR,CY,2017,11.99,11.99 e,e
5,01000,PROD_BP,MIO_EUR,CZ,2017,1062.51,1062.51 e,e
6,01000,PROD_BP,MIO_EUR,DE,2017,4530.67,4530.67 e,e
7,01000,PROD_BP,MIO_EUR,DK,2017,1761.17,1761.17 e,e
8,01000,PROD_BP,MIO_EUR,EA11,2017,26275.97,26275.97 e,e
9,01000,PROD_BP,MIO_EUR,EA12,2017,27068.94,27068.94 e,e
10,01000,PROD_BP,MIO_EUR,EA16,2017,27687.53,27687.53 e,e
11,01000,PROD_BP,MIO_EUR,EA19,2017,29190.75,29190.75 e,e
12,01000,PROD_BP,MIO_EUR,EE,2017,215.69,215.69 e,e
13,01000,PROD_BP,MIO_EUR,EL,2017,792.97,792.97 e,e
14,01000,PROD_BP,MIO_EUR,ES,2017,3293.19,3293.19 e,e
15,01000,PROD_BP,MIO_EUR,EU15,2017,32865.12,32865.12 e,e
16,01000,PROD_BP,MIO_EUR,EU25,2017,41732.66,41732.66 e,e
17,01000,PROD_BP,MIO_EUR,EU27,2017,47182.21,47182.21 e,e
18,01000,PROD_BP,MIO_EUR,EU28,2017,47749.82,47749.82 e,e
19,01000,PROD_BP,MIO_EUR,FI,2017,419.28,419.28 e,e
20,01000,PROD_BP,MIO_EUR,FR,2017,12450.13,12450.13 e,e
21,01000,PROD_BP,MIO_EUR,HR,2017,567.60,567.60 e,e
22,01000,PROD_BP,MIO_EUR,HU,2017,1989.43,1989.43 e,e
23,01000,PROD_BP,MIO_EUR,IE,2017,337.49,337.49 e,e
24,01000,PROD_BP,MIO_EUR,IS,2017,NaN,:,
25,01000,PROD_BP,MIO_EUR,IT,2017,3344.59,3344.59 e,e
26,01000,PROD_BP,MIO_EUR,LT,2017,893.53,893.53 e,e
27,01000,PROD_BP,MIO_EUR,LU,2017,22.77,22.77 e,e
28,01000,PROD_BP,MIO_EUR,LV,2017,394.00,394.00 e,e
29,01000,PROD_BP,MIO_EUR,MK,2017,NaN,:,
...,...,...,...,...,...,...,...,...
2337855,35000,PROD_BP,MIO_PPS,EA16,1973,NaN,:,
2337856,35000,PROD_BP,MIO_PPS,EA19,1973,NaN,:,
2337857,35000,PROD_BP,MIO_PPS,EE,1973,NaN,:,
2337858,35000,PROD_BP,MIO_PPS,EL,1973,NaN,:,
2337859,35000,PROD_BP,MIO_PPS,ES,1973,NaN,:,
2337860,35000,PROD_BP,MIO_PPS,EU15,1973,NaN,:,
2337861,35000,PROD_BP,MIO_PPS,EU25,1973,NaN,:,
2337862,35000,PROD_BP,MIO_PPS,EU27,1973,NaN,:,
2337863,35000,PROD_BP,MIO_PPS,EU28,1973,NaN,:,
2337864,35000,PROD_BP,MIO_PPS,FI,1973,NaN,:,
2337865,35000,PROD_BP,MIO_PPS,FR,1973,NaN,:,
2337866,35000,PROD_BP,MIO_PPS,HR,1973,NaN,:,
2337867,35000,PROD_BP,MIO_PPS,HU,1973,NaN,:,
2337868,35000,PROD_BP,MIO_PPS,IE,1973,NaN,:,
2337869,35000,PROD_BP,MIO_PPS,IS,1973,NaN,:,
2337870,35000,PROD_BP,MIO_PPS,IT,1973,NaN,:,
2337871,35000,PROD_BP,MIO_PPS,LT,1973,NaN,:,
2337872,35000,PROD_BP,MIO_PPS,LU,1973,NaN,:,
2337873,35000,PROD_BP,MIO_PPS,LV,1973,NaN,:,
2337874,35000,PROD_BP,MIO_PPS,MK,1973,NaN,:,
2337875,35000,PROD_BP,MIO_PPS,MT,1973,NaN,:,
2337876,35000,PROD_BP,MIO_PPS,NL,1973,NaN,:,
2337877,35000,PROD_BP,MIO_PPS,NO,1973,NaN,:,
2337878,35000,PROD_BP,MIO_PPS,PL,1973,NaN,:,
2337879,35000,PROD_BP,MIO_PPS,PT,1973,NaN,:,
2337880,35000,PROD_BP,MIO_PPS,RO,1973,NaN,:,
2337881,35000,PROD_BP,MIO_PPS,SE,1973,NaN,:,
2337882,35000,PROD_BP,MIO_PPS,SI,1973,NaN,:,
2337883,35000,PROD_BP,MIO_PPS,SK,1973,NaN,:,
2337884,35000,PROD_BP,MIO_PPS,UK,1973,NaN,:,